function plotdata(X1, Y1, X2, Y2)
%PLOTDATA(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 26-Apr-2015 15:42:18

% Create figure
figure1 = figure;%('visible','off');
scrsz = get(0,'ScreenSize');
set(figure1, 'Position',[scrsz(3)-1000 scrsz(4)-800 scrsz(3)/3 scrsz(4)/2])
% Create axes
axes1 = axes('Parent',figure1,'FontName','Lucida Sans');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',1);

% Create plot
plot(X2,Y2,'Color',[1 0 0],'LineWidth',1);

% Create xlabel
xlabel('Height (um)','FontSize',12,'FontName','Lucida Sans');

% Create ylabel
ylabel('Deflection (nm)','FontSize',12,'FontName','Lucida Sans');

